from typing import Literal


Categories = Literal['Furniture',
                     'Home Improvement',
                     'Décor & Pillows',
                     'Outdoor',
                     'Storage & Organization',
                     'Lighting',
                     'Rugs',
                     'Bed & Bath',
                     'Kitchen & Tabletop',
                     'Baby & Kids',
                     'School Furniture and Supplies',
                     'Appliances',
                     'Holiday Décor',
                     'Commercial Business Furniture',
                     'Pet',
                     'Contractor',
                     'Sale',
                     'Foodservice ',
                     'Reception Area']


SubCategories = Literal['Living Room Furniture',
                        'Kitchen & Dining Furniture',
                        'Bedroom Furniture',
                        'Bathroom Remodel & Bathroom Fixtures',
                        'Office Furniture',
                        'Outdoor & Patio Furniture',
                        'Flooring, Walls & Ceiling',
                        'Area Rugs',
                        'Hardware',
                        'Bedding',
                        'Tableware & Drinkware',
                        'Window Treatments',
                        'Decorative Pillows & Blankets',
                        'Garage & Outdoor Storage & Organization',
                        'Wall Décor',
                        'Art',
                        'Garden',
                        'Toddler & Kids Bedroom Furniture',
                        'Outdoor Décor',
                        'Home Accessories',
                        'Ceiling Lights',
                        'Wall Lights',
                        'Mirrors',
                        'Bathroom Storage & Organization',
                        'Kitchen Mats',
                        'Area Rugs',
                        'Table & Floor Lamps',
                        'Outdoor Lighting',
                        'Light Bulbs & Hardware',
                        'Wall Shelving & Organization',
                        'Flowers & Plants',
                        'Kitchen Remodel & Kitchen Fixtures',
                        'Clocks',
                        'Doormats',
                        'Shower Curtains & Accessories',
                        'Kitchen Organization',
                        'Mattresses & Foundations',
                        'Toddler & Kids Playroom',
                        'Doors & Door Hardware',
                        'Bedding Essentials',
                        'Shoe Storage',
                        'Closet Storage & Organization',
                        'Kitchen Appliances',
                        'Outdoor Shades',
                        'Cookware & Bakeware',
                        'Bathroom Accessories & Organization',
                        'Kitchen Utensils & Tools',
                        'Game Tables & Game Room Furniture',
                        'Facilities & Maintenance',
                        'Storage Containers & Drawers',
                        'Small Kitchen Appliances',
                        'School Furniture',
                        'Christmas',
                        'Commercial Office Furniture',
                        'Nursery Bedding',
                        'Entry & Hallway',
                        'Baby & Kids Décor & Lighting',
                        'Plumbing',
                        'Candles & Holders',
                        'Outdoor Recreation',
                        'Ceiling Fans',
                        'Dog']
