from typing import Literal, get_args


Categories = Literal['Furniture',
                     'Home Improvement',
                     'Décor & Pillows',
                     'Outdoor',
                     'Storage & Organization',
                     'Lighting',
                     'Rugs',
                     'Bed & Bath',
                     'Kitchen & Tabletop',
                     'Baby & Kids',
                     'School Furniture and Supplies',
                     'Appliances',
                     'Holiday Décor',
                     'Commercial Business Furniture',
                     'Pet',
                     'Contractor',
                     'Sale',
                     'Foodservice ',
                     'Reception Area',
                     'No Category Fits']


CategoriesReversed = Literal['No Category Fits',
                             'Reception Area',
                             'Foodservice ',
                             'Contractor',
                             'Pet',
                             'Commercial Business Furniture',
                             'Holiday Décor',
                             'Appliances',
                             'School Furniture and Supplies',
                             'Baby & Kids',
                             'Kitchen & Tabletop',
                             'Bed & Bath',
                             'Rugs',
                             'Lighting',
                             'Storage & Organization',
                             'Outdoor',
                             'Décor & Pillows',
                             'Home Improvement',
                             'Furniture']


categories = list(get_args(Categories))


SubCategories = Literal['Living Room Furniture',
                        'Kitchen & Dining Furniture',
                        'Bedroom Furniture',
                        'Bathroom Remodel & Bathroom Fixtures',
                        'Office Furniture',
                        'Outdoor & Patio Furniture',
                        'Flooring, Walls & Ceiling',
                        'Area Rugs',
                        'Hardware',
                        'Bedding',
                        'Tableware & Drinkware',
                        'Window Treatments',
                        'Decorative Pillows & Blankets',
                        'Garage & Outdoor Storage & Organization',
                        'Wall Décor',
                        'Art',
                        'Garden',
                        'Toddler & Kids Bedroom Furniture',
                        'Outdoor Décor',
                        'Home Accessories',
                        'Ceiling Lights',
                        'Wall Lights',
                        'Mirrors',
                        'Bathroom Storage & Organization',
                        'Kitchen Mats',
                        'Area Rugs',
                        'Table & Floor Lamps',
                        'Outdoor Lighting',
                        'Light Bulbs & Hardware',
                        'Wall Shelving & Organization',
                        'Flowers & Plants',
                        'Kitchen Remodel & Kitchen Fixtures',
                        'Clocks',
                        'Doormats',
                        'Shower Curtains & Accessories',
                        'Kitchen Organization',
                        'Mattresses & Foundations',
                        'Toddler & Kids Playroom',
                        'Doors & Door Hardware',
                        'Bedding Essentials',
                        'Shoe Storage',
                        'Closet Storage & Organization',
                        'Kitchen Appliances',
                        'Outdoor Shades',
                        'Cookware & Bakeware',
                        'Bathroom Accessories & Organization',
                        'Kitchen Utensils & Tools',
                        'Game Tables & Game Room Furniture',
                        'Facilities & Maintenance',
                        'Storage Containers & Drawers',
                        'Small Kitchen Appliances',
                        'School Furniture',
                        'Christmas',
                        'Commercial Office Furniture',
                        'Nursery Bedding',
                        'Entry & Hallway',
                        'Baby & Kids Décor & Lighting',
                        'Plumbing',
                        'Candles & Holders',
                        'Outdoor Recreation',
                        'Ceiling Fans',
                        'Dog',
                        'No SubCategory Fits']


subcategories = list(get_args(SubCategories))


FullyQualifiedCategories = Literal['Furniture  /  Living Room Furniture ',
                                   'Furniture  /  Kitchen & Dining Furniture ',
                                   'Furniture  /  Bedroom Furniture ',
                                   'Home Improvement  /  Bathroom Remodel & Bathroom Fixtures ',
                                   'Furniture  /  Office Furniture ',
                                   'Outdoor  /  Outdoor & Patio Furniture ',
                                   ' No Category Fits ',
                                   'Home Improvement  /  Flooring, Walls & Ceiling ',
                                   'Rugs  /  Area Rugs',
                                   'Home Improvement  /  Hardware ',
                                   'Bed & Bath  /  Bedding ',
                                   'Kitchen & Tabletop  /  Tableware & Drinkware ',
                                   'Décor & Pillows  /  Window Treatments ',
                                   'Décor & Pillows  /  Decorative Pillows & Blankets ',
                                   'Décor & Pillows  /  Wall Décor ',
                                   'Storage & Organization  /  Garage & Outdoor Storage & Organization ',
                                   'Décor & Pillows  /  Art ',
                                   'Outdoor  /  Garden ',
                                   'Baby & Kids  /  Toddler & Kids Bedroom Furniture ',
                                   'Outdoor  /  Outdoor Décor ',
                                   'Décor & Pillows  /  Home Accessories ',
                                   'Lighting  /  Ceiling Lights ',
                                   'Lighting  /  Wall Lights ',
                                   'Décor & Pillows  /  Mirrors ',
                                   'Storage & Organization  /  Bathroom Storage & Organization ',
                                   'Rugs  /  Kitchen Mats',
                                   'Rugs  /  Area Rugs ',
                                   'Lighting  /  Table & Floor Lamps ',
                                   'Lighting  /  Outdoor Lighting ',
                                   'Lighting  /  Light Bulbs & Hardware ',
                                   'Storage & Organization  /  Wall Shelving & Organization ',
                                   'Décor & Pillows  /  Flowers & Plants ',
                                   'Home Improvement  /  Kitchen Remodel & Kitchen Fixtures ',
                                   'Décor & Pillows  /  Clocks ',
                                   'Rugs  /  Doormats',
                                   'Bed & Bath  /  Shower Curtains & Accessories ',
                                   'Kitchen & Tabletop  /  Kitchen Organization ',
                                   'Bed & Bath  /  Mattresses & Foundations ',
                                   'Baby & Kids  /  Toddler & Kids Playroom ',
                                   'Home Improvement  /  Doors & Door Hardware ',
                                   'Bed & Bath  /  Bedding Essentials ',
                                   'Storage & Organization  /  Shoe Storage ',
                                   'Storage & Organization  /  Closet Storage & Organization ',
                                   'Appliances  /  Kitchen Appliances ',
                                   'Outdoor  /  Outdoor Shades ',
                                   'Kitchen & Tabletop  /  Cookware & Bakeware ',
                                   'Kitchen & Tabletop  /  Kitchen Utensils & Tools ',
                                   'Bed & Bath  /  Bathroom Accessories & Organization ',
                                   'Furniture  /  Game Tables & Game Room Furniture ',
                                   'School Furniture and Supplies  /  Facilities & Maintenance ',
                                   'Storage & Organization  /  Storage Containers & Drawers ',
                                   'Kitchen & Tabletop  /  Small Kitchen Appliances ',
                                   'School Furniture and Supplies  /  School Furniture ',
                                   'Holiday Décor  /  Christmas ',
                                   'Commercial Business Furniture  /  Commercial Office Furniture ',
                                   'Baby & Kids  /  Nursery Bedding ',
                                   'Contractor  /  Entry & Hallway ',
                                   'Baby & Kids  /  Baby & Kids Décor & Lighting ',
                                   'Home Improvement  /  Plumbing ',
                                   'Décor & Pillows  /  Candles & Holders ',
                                   'Outdoor  /  Outdoor Recreation ',
                                   'Lighting  /  Ceiling Fans ',
                                   'Pet  /  Dog ',
                                   'Décor & Pillows  /  Picture Frames & Albums ',
                                   'Outdoor  /  Front Door Décor & Curb Appeal ',
                                   'Appliances  /  Washers & Dryers ',
                                   'Storage & Organization  /  Storage Furniture ',
                                   'Sale  /  Closeout ',
                                   'Outdoor  /  Outdoor Cooking & Tableware ',
                                   'School Furniture and Supplies  /  School Boards & Technology ',
                                   'Outdoor  /  Hot Tubs & Saunas ',
                                   'Outdoor  /  Outdoor Fencing & Flooring ',
                                   'Pet  /  Bird ',
                                   'Storage & Organization  /  Jewelry Organization ',
                                   'Bed & Bath  /  Bath Rugs & Towels ',
                                   'School Furniture and Supplies  /  School Spaces ',
                                   'Baby & Kids  /  Teen Bedroom Furniture ',
                                   'Storage & Organization  /  Cleaning & Laundry Organization ',
                                   'Baby & Kids  /  Nursery Furniture ',
                                   'Holiday Décor  /  Holiday Lighting',
                                   'Commercial Business Furniture  /  Boards & Tech Accessories ',
                                   'Contractor  /  Commercial Contractor ',
                                   'Foodservice  /  Commercial Kitchen ',
                                   'Foodservice  /  Foodservice Tables ',
                                   'Bed Accessories / ',
                                   'Baby & Kids  /  Baby & Kids Storage ',
                                   'Shop Product Type  /  Chairs ',
                                   'Reception Area  /  Reception Seating ',
                                   'Clips / Clamps',
                                   'Outdoor  /  Outdoor Heating ',
                                   'Home Improvement  /  Building Equipment ',
                                   'Home Improvement  /  Heating, Cooling & Air Quality ',
                                   'Holiday Décor  /  Holiday Lighting ',
                                   'Storage & Organization  /  Storage & Organization Sale',
                                   'Protection Plans / ',
                                   'Furniture  /  Entry & Mudroom Furniture ',
                                   'Storage & Organization  /  Office Organization ']
