repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
  - repo: local
    hooks:
      - id: poetry-check-lock
        name: poetry lock is current
        entry: poetry check --lock
        language: system
        pass_filenames: false
        files: ^(pyproject\.toml|poetry\.lock)$
      - id: pytest-unit
        name: pytest unit
        entry: poetry run pytest tests/unit
        language: system
        pass_filenames: false
